-- Seed a first scheduled transaction when a subscription is created.
--
-- Problem: the UI shows subscription "history" based on existing rows in `transactions`,
-- but subscription billing rows are only generated by a daily job when `next_billing_date <= today`.
-- When the first charge date is in the future, users see an empty history and think it failed.
--
-- Solution: on INSERT into `workspace_subscriptions`, create one `transactions` row dated at the
-- first charge date (next_billing_date/start_date). The daily billing job remains responsible
-- for advancing `next_billing_date` when the date becomes due; this trigger only seeds visibility.

create or replace function public.seed_subscription_first_transaction()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_charge date;
  v_ts timestamptz;
begin
  -- Prefer next_billing_date; fall back to start_date for legacy rows.
  v_charge := coalesce(new.next_billing_date, new.start_date);

  -- If we don't have a charge date, there's nothing to seed.
  if v_charge is null then
    return new;
  end if;

  -- Idempotency: avoid duplicates for the same subscription + calendar date (UTC).
  if exists (
    select 1
    from public.transactions t
    where t.subscription_id = new.id
      and (t.date at time zone 'UTC')::date = v_charge
  ) then
    return new;
  end if;

  -- Match the billing RPC convention (noon UTC) to avoid date-boundary issues.
  v_ts := (to_char(v_charge, 'YYYY-MM-DD') || 'T12:00:00Z')::timestamptz;

  insert into public.transactions (
    user_id,
    workspace_id,
    wallet_id,
    category_id,
    type,
    amount,
    description,
    date,
    is_recurring,
    recurring_interval,
    subscription_id,
    payment_method,
    payment_credit_card_id
  ) values (
    new.user_id,
    new.workspace_id,
    new.wallet_id,
    new.category_id,
    'expense',
    new.amount,
    new.name,
    v_ts,
    false,
    null,
    new.id,
    new.payment_method,
    new.payment_credit_card_id
  );

  return new;
end;
$$;

revoke all on function public.seed_subscription_first_transaction() from public;
grant execute on function public.seed_subscription_first_transaction() to service_role;

drop trigger if exists seed_workspace_subscription_first_transaction on public.workspace_subscriptions;
create trigger seed_workspace_subscription_first_transaction
after insert on public.workspace_subscriptions
for each row execute function public.seed_subscription_first_transaction();

